// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT03EnviarMensagemTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT03EnviarMensagem() {
    driver.get("https://inoveteste.com.br/");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("#nav-menu-item-5643 font:nth-child(1) > font:nth-child(1) > font:nth-child(1) > font:nth-child(1) > font:nth-child(1) > font:nth-child(1)")).click();
    driver.findElement(By.name("nome")).sendKeys("´Jordan Lamburg");
    driver.findElement(By.name("email")).sendKeys("Bytedojan@pou.com.br");
    driver.findElement(By.name("assunto")).click();
    driver.findElement(By.name("mensagem")).click();
    driver.findElement(By.name("mensagem")).sendKeys("show");
    driver.findElement(By.cssSelector(".qodef-content-aligment-left .qodef-section-inner-margin")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) .wpcf7-form-control")).click();
  }
}
